food = input("What type of food do you like?: ")
plant = input("what type of plant you like:")
cookingType = input("what is a way to cook something?:")
burntFood = input("How do you describe burnt food?:")
householdItem = input("Nmae something in you house?:")
print()
print("Tonights dinner")
print("For dinner you should make", cookingType, food, "with", burntFood, plant, "on a plate of", householdItem)
